// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ZTtDRPk1m_ZC9WeHdzxh-2pqX-cOuTM',
    appId: '1:381882045030:web:dee83ce30ec9333fc653a7',
    messagingSenderId: '381882045030',
    projectId: 'med-bot-39c5c',
    authDomain: 'med-bot-39c5c.firebaseapp.com',
    storageBucket: 'med-bot-39c5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrIV8kWxD_VruUjHfYiXgc2I1STz7WqM',
    appId: '1:381882045030:android:904aeb3ef5b70a03c653a7',
    messagingSenderId: '381882045030',
    projectId: 'med-bot-39c5c',
    storageBucket: 'med-bot-39c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMT-ROUZ4VDp7wWafYbX5NGL-dBJzRes',
    appId: '1:381882045030:ios:c21262481a032d3dc653a7',
    messagingSenderId: '381882045030',
    projectId: 'med-bot-39c5c',
    storageBucket: 'med-bot-39c5c.appspot.com',
    iosClientId: '381882045030-ebl4htjmb9l3lt2d15dmqbsjf04uacuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.medbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXMT-ROUZ4VDp7wWafYbX5NGL-dBJzRes',
    appId: '1:381882045030:ios:9639da007c93f0e3c653a7',
    messagingSenderId: '381882045030',
    projectId: 'med-bot-39c5c',
    storageBucket: 'med-bot-39c5c.appspot.com',
    iosClientId: '381882045030-egb1uh957gh8q69b1760sjcfajg3f3ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.medbot.RunnerTests',
  );
}
